<?php
    // Login
    define('LOGIN_SUCCESS', 'LOGIN_SUCCESS');
    define('LOGIN_FAIL', 'LOGIN_FAIL');
    define('EMPTY_EMAIL', 'EMPTY_EMAIL');
    define('EMPTY_PASSWORD', 'EMPTY_PASSWORD');
    define('FORMAT_INVALID_EMAIL', 'FORMAT_INVALID_EMAIL');

    // Logout
    define('EMPTY_TOKEN', 'EMPTY_TOKEN');
    define('LOGOUT_SUCCESS', 'LOGOUT_SUCCESS');
    define('LOGOUT_FAIL', 'LOGOUT_FAIL');
    define('REFRESH_TOKEN_SUCCESS', 'REFRESH_TOKEN_SUCCESS');

    // Member
    define('EMPTY_FULLNAME', 'EMPTY_FULLNAME');
    define('EMPTY_IS_MALE', 'EMPTY_IS_MALE');
    define('EMPTY_BIRTHDAY', 'EMPTY_BIRTHDAY');
    define('EMPTY_PHONE', 'EMPTY_PHONE');
    define('EMPTY_PICTURE', 'EMPTY_PICTURE');
    define('FORMAT_INVALID_IS_MALE', 'FORMAT_INVALID_IS_MALE');
    define('FORMAT_INVALID_BIRTHDAY', 'FORMAT_INVALID_BIRTHDAY');
    define('FORMAT_INVALID_PHONE', 'FORMAT_INVALID_PHONE');
    define('FORMAT_INVALID_IMAGE', 'FORMAT_INVALID_IMAGE');
    define('MAX_SIZE_PICTURE', 'MAX_SIZE_PICTURE');
    define('MEMBER_NOT_FOUND', 'MEMBER_NOT_FOUND');
    define('UPLOAD_AVATAR_NOT_SUCCESS', 'UPLOAD_AVATAR_NOT_SUCCESS');
    define('UPDATE_MEMBER_NOT_SUCCESS', 'UPDATE_MEMBER_NOT_SUCCESS');
    define('UPDATE_PROFILE_SUCCESS', 'UPDATE_PROFILE_SUCCESS');
    