<?php
    // Url
    define('URL_IMAGE_MEMBER', 'public/images/member/');
    define('URL_IMAGE_MEMBER_THUMB', 'public/images/member/thumbnail/');

    define('WIDTH_AVATAR_THUMB', 180);
    define('HEIGHT_AVATAR_THUMB', 180);
    define('THUMB_SIZE', WIDTH_AVATAR_THUMB."x".HEIGHT_AVATAR_THUMB);

    // Common
    define('NOT_FOUND', 'NOT_FOUND');

    // Login
    define('LOGIN_SUCCESS', 'LOGIN_SUCCESS');
    define('LOGIN_FAIL', 'LOGIN_FAIL');
    define('EMPTY_EMAIL', 'EMPTY_EMAIL');
    define('EMPTY_PASSWORD', 'EMPTY_PASSWORD');
    define('FORMAT_INVALID_EMAIL', 'FORMAT_INVALID_EMAIL');

    // Logout
    define('EMPTY_TOKEN', 'EMPTY_TOKEN');
    define('LOGOUT_SUCCESS', 'LOGOUT_SUCCESS');
    define('LOGOUT_FAIL', 'LOGOUT_FAIL');
    define('REFRESH_TOKEN_SUCCESS', 'REFRESH_TOKEN_SUCCESS');

    // Member
    define('EMPTY_FULLNAME', 'EMPTY_FULLNAME');
    define('EMPTY_IS_MALE', 'EMPTY_IS_MALE');
    define('EMPTY_BIRTHDAY', 'EMPTY_BIRTHDAY');
    define('EMPTY_PHONE', 'EMPTY_PHONE');
    define('EMPTY_PICTURE', 'EMPTY_PICTURE');
    define('FORMAT_INVALID_IS_MALE', 'FORMAT_INVALID_IS_MALE');
    define('FORMAT_INVALID_BIRTHDAY', 'FORMAT_INVALID_BIRTHDAY');
    define('FORMAT_INVALID_PHONE', 'FORMAT_INVALID_PHONE');
    define('FORMAT_INVALID_IMAGE', 'FORMAT_INVALID_IMAGE');
    define('MAX_SIZE_PICTURE', 'MAX_SIZE_PICTURE');
    define('MEMBER_NOT_FOUND', 'MEMBER_NOT_FOUND');
    define('UPLOAD_AVATAR_NOT_SUCCESS', 'UPLOAD_AVATAR_NOT_SUCCESS');
    define('UPDATE_MEMBER_NOT_SUCCESS', 'UPDATE_MEMBER_NOT_SUCCESS');
    define('UPDATE_PROFILE_SUCCESS', 'UPDATE_PROFILE_SUCCESS');

    // Config
    define('GET_CONFIG_SUCCESS', 'GET_CONFIG_SUCCESS');
    define('GET_CONFIG_FAIL', 'GET_CONFIG_FAIL');
    define('EMPTY_TYPE', 'EMPTY_TYPE');
    define('EMPTY_VALUE', 'EMPTY_VALUE');
    define('CONFIG_NOT_FOUND', 'CONFIG_NOT_FOUND');
    define('CREATE_CONFIG_SUCCESS', 'CREATE_CONFIG_SUCCESS');
    define('CREATE_CONFIG_FAIL', 'CREATE_CONFIG_FAIL');
    define('UPDATE_CONFIG_SUCCESS', 'UPDATE_CONFIG_SUCCESS');
    define('UPDATE_CONFIG_FAIL', 'UPDATE_CONFIG_FAIL');
    define('DELETE_CONFIG_SUCCESS', 'DELETE_CONFIG_SUCCESS');
    define('DELETE_CONFIG_FAIL', 'DELETE_CONFIG_FAIL');